name: firedart
description: A dart-native implementation of the Firebase Auth and Firestore SDKs.
version: 0.9.8
homepage: https://github.com/cachapa/firedart

environment:
  sdk: '>=2.18.0 <4.0.0'

dependencies:
  http: '>=0.13.0 <2.0.0'
  protobuf: ^3.1.0
  fixnum: ^1.1.0
  grpc:

dev_dependencies:
  lints: any
  test: any

